import { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Classic Solitaire Diamond Ring',
    description: 'Elegant 18K white gold solitaire ring featuring a stunning 1.5 carat GIA certified round brilliant diamond. Timeless design perfect for engagements.',
    category: 'rings',
    price: 8500,
    images: ['/products/ring-1.jpg'],
    featured: true,
    inStock: true,
    specifications: {
      material: '18K White Gold',
      gemstone: '1.5ct Round Brilliant Diamond',
      certification: 'GIA Certified',
      weight: '3.2g',
    },
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Vintage Halo Engagement Ring',
    description: 'Exquisite vintage-inspired halo ring with a 2.0 carat IGI certified cushion cut diamond surrounded by micro-pavé diamonds.',
    category: 'rings',
    price: 12500,
    images: ['/products/ring-2.jpg'],
    featured: true,
    inStock: true,
    specifications: {
      material: '18K Yellow Gold',
      gemstone: '2.0ct Cushion Cut Diamond',
      certification: 'IGI Certified',
      weight: '4.5g',
    },
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: '3',
    name: 'Diamond Tennis Necklace',
    description: 'Stunning 16-inch tennis necklace featuring 50 perfectly matched round brilliant diamonds totaling 10 carats.',
    category: 'necklaces',
    price: 15000,
    images: ['/products/necklace-1.jpg'],
    featured: true,
    inStock: true,
    specifications: {
      material: '18K White Gold',
      gemstone: '10ct Total Diamond Weight',
      certification: 'GIA Certified',
      dimensions: '16 inches',
    },
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
  },
  {
    id: '4',
    name: 'Sapphire & Diamond Pendant',
    description: 'Beautiful pendant featuring a 3 carat Ceylon sapphire surrounded by a halo of brilliant diamonds on an 18K white gold chain.',
    category: 'necklaces',
    price: 6800,
    images: ['/products/necklace-2.jpg'],
    featured: false,
    inStock: true,
    specifications: {
      material: '18K White Gold',
      gemstone: '3ct Ceylon Sapphire, 0.5ct Diamonds',
      certification: 'IGI Certified',
      dimensions: '18 inches',
    },
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-02-10T10:00:00Z',
  },
  {
    id: '5',
    name: 'Diamond Stud Earrings',
    description: 'Classic diamond stud earrings featuring two perfectly matched 1 carat GIA certified round brilliant diamonds.',
    category: 'earrings',
    price: 9500,
    images: ['/products/earrings-1.jpg'],
    featured: true,
    inStock: true,
    specifications: {
      material: '18K White Gold',
      gemstone: '2ct Total Diamond Weight',
      certification: 'GIA Certified',
      weight: '2.1g',
    },
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
  },
  {
    id: '6',
    name: 'Emerald Drop Earrings',
    description: 'Elegant drop earrings featuring Colombian emeralds and diamond accents in 18K yellow gold.',
    category: 'earrings',
    price: 7200,
    images: ['/products/earrings-2.jpg'],
    featured: false,
    inStock: true,
    specifications: {
      material: '18K Yellow Gold',
      gemstone: '2ct Colombian Emeralds, 0.3ct Diamonds',
      certification: 'IGI Certified',
      dimensions: '1.5 inches',
    },
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-02-20T10:00:00Z',
  },
  {
    id: '7',
    name: 'Diamond Tennis Bracelet',
    description: 'Luxurious 7-inch tennis bracelet featuring 40 round brilliant diamonds totaling 8 carats.',
    category: 'bracelets',
    price: 11500,
    images: ['/products/bracelet-1.jpg'],
    featured: true,
    inStock: true,
    specifications: {
      material: '18K White Gold',
      gemstone: '8ct Total Diamond Weight',
      certification: 'GIA Certified',
      dimensions: '7 inches',
    },
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: '8',
    name: 'Ruby & Diamond Bangle',
    description: 'Stunning bangle bracelet featuring alternating rubies and diamonds in 18K rose gold.',
    category: 'bracelets',
    price: 8900,
    images: ['/products/bracelet-2.jpg'],
    featured: false,
    inStock: false,
    specifications: {
      material: '18K Rose Gold',
      gemstone: '3ct Rubies, 2ct Diamonds',
      certification: 'IGI Certified',
      weight: '15.2g',
    },
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-03-05T10:00:00Z',
  },
  {
    id: '9',
    name: 'Three Stone Diamond Ring',
    description: 'Symbolic three stone ring representing past, present, and future with GIA certified diamonds.',
    category: 'rings',
    price: 10200,
    images: ['/products/ring-3.jpg'],
    featured: false,
    inStock: true,
    specifications: {
      material: 'Platinum',
      gemstone: '3ct Total Diamond Weight',
      certification: 'GIA Certified',
      weight: '5.8g',
    },
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '10',
    name: 'Pearl & Diamond Necklace',
    description: 'Sophisticated necklace featuring South Sea pearls and diamond accents.',
    category: 'necklaces',
    price: 5600,
    images: ['/products/necklace-3.jpg'],
    featured: false,
    inStock: true,
    specifications: {
      material: '18K White Gold',
      gemstone: 'South Sea Pearls, 0.8ct Diamonds',
      certification: 'IGI Certified',
      dimensions: '20 inches',
    },
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2024-03-15T10:00:00Z',
  },
  {
    id: '11',
    name: 'Rolex Submariner Date',
    description: 'Iconic Rolex Submariner Date in stainless steel with black ceramic bezel. 41mm case, automatic movement, 300m water resistance.',
    category: 'watches',
    price: 12500,
    images: ['/products/watch-1.jpg'],
    featured: true,
    inStock: true,
    specifications: {
      material: 'Stainless Steel',
      dimensions: '41mm case diameter',
      certification: 'Rolex Certified',
      weight: '155g',
    },
    createdAt: '2024-03-20T10:00:00Z',
    updatedAt: '2024-03-20T10:00:00Z',
  },
  {
    id: '12',
    name: 'Omega Seamaster Aqua Terra',
    description: 'Elegant Omega Seamaster Aqua Terra with blue dial and stainless steel bracelet. Co-Axial Master Chronometer movement.',
    category: 'watches',
    price: 6800,
    images: ['/products/watch-2.jpg'],
    featured: true,
    inStock: true,
    specifications: {
      material: 'Stainless Steel',
      dimensions: '41mm case diameter',
      certification: 'METAS Certified',
      weight: '175g',
    },
    createdAt: '2024-03-22T10:00:00Z',
    updatedAt: '2024-03-22T10:00:00Z',
  },
  {
    id: '13',
    name: 'Cartier Tank Must',
    description: 'Classic Cartier Tank Must with silver-grained dial and blue steel hands. Elegant dress watch with quartz movement.',
    category: 'watches',
    price: 3200,
    images: ['/products/watch-3.jpg'],
    featured: false,
    inStock: true,
    specifications: {
      material: 'Stainless Steel',
      dimensions: '33.7mm x 25.5mm',
      certification: 'Cartier Certified',
      weight: '85g',
    },
    createdAt: '2024-03-25T10:00:00Z',
    updatedAt: '2024-03-25T10:00:00Z',
  },
  {
    id: '14',
    name: 'Patek Philippe Calatrava',
    description: 'Timeless Patek Philippe Calatrava in 18K white gold with silver dial. Manual winding movement, the epitome of dress watch elegance.',
    category: 'watches',
    price: 28500,
    images: ['/products/watch-4.jpg'],
    featured: true,
    inStock: true,
    specifications: {
      material: '18K White Gold',
      dimensions: '39mm case diameter',
      certification: 'Patek Philippe Seal',
      weight: '95g',
    },
    createdAt: '2024-03-28T10:00:00Z',
    updatedAt: '2024-03-28T10:00:00Z',
  },
  {
    id: '15',
    name: 'Audemars Piguet Royal Oak',
    description: 'Iconic Audemars Piguet Royal Oak in stainless steel with blue "Grande Tapisserie" dial. Automatic movement, integrated bracelet design.',
    category: 'watches',
    price: 32000,
    images: ['/products/watch-5.jpg'],
    featured: true,
    inStock: true,
    specifications: {
      material: 'Stainless Steel',
      dimensions: '41mm case diameter',
      certification: 'AP Certified',
      weight: '185g',
    },
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2024-04-01T10:00:00Z',
  },
  {
    id: '16',
    name: 'Jaeger-LeCoultre Reverso',
    description: 'Classic Jaeger-LeCoultre Reverso with reversible case in stainless steel. Art Deco design with manual winding movement.',
    category: 'watches',
    price: 8900,
    images: ['/products/watch-6.jpg'],
    featured: false,
    inStock: true,
    specifications: {
      material: 'Stainless Steel',
      dimensions: '42.9mm x 25.5mm',
      certification: 'JLC Certified',
      weight: '92g',
    },
    createdAt: '2024-04-03T10:00:00Z',
    updatedAt: '2024-04-03T10:00:00Z',
  },
  {
    id: '17',
    name: 'IWC Portugieser Chronograph',
    description: 'Elegant IWC Portugieser Chronograph in 18K rose gold with silver dial. Classic design with in-house automatic chronograph movement.',
    category: 'watches',
    price: 24500,
    images: ['/products/watch-7.jpg'],
    featured: false,
    inStock: true,
    specifications: {
      material: '18K Rose Gold',
      dimensions: '41mm case diameter',
      certification: 'IWC Certified',
      weight: '145g',
    },
    createdAt: '2024-04-05T10:00:00Z',
    updatedAt: '2024-04-05T10:00:00Z',
  },
];

export function getProducts(): Product[] {
  return mockProducts;
}

export function getProductById(id: string): Product | undefined {
  return mockProducts.find(p => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return mockProducts.filter(p => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return mockProducts.filter(p => p.featured);
}
